### ISSUE TITLE
Don't prevent scrolling if swipe up/down is not used

### ISSUE THREAD

**Issue by Jigsaw5279** [stephband/jquery.event.swipe#33]
Is there any way to still let scrolling happen if the container has one of the swipe events attached to it?
I only wanted to catch left/right swipe, but now I cant scroll within that container at all..

**Comment by stephband** [comment]
Read the docs at: http://stephband.info/jquery.event.swipe/#scroll

This issue has been covered before: https://github.com/stephband/jquery.event.swipe/issues/26

**Comment by K4T** [comment]
Unfortuatelly still happens on iPhone5 even with code from the docs :/

**Comment by rulrok** [comment]
IT keeps happening on iphone4s as well.
